config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'forums#index'
  resources :forums
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_main.rb
class ForumMain < ApplicationRecord
  has_many :topics, :dependent => :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :forum
  has_many :posts, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
    @forums = ForumMain.all 
  end

  def edit
    @forum = ForumMain.find(params[:id])
  end

  def show
  end

  def create
    @forum = ForumMain.new(forum_params)
    @forum.save
  end

  def new
  end

    private

  def forum_params
    params.require(:forum).permit(:name, :description)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/forums/create.html.erb
    <h1> Thank you! </h1>
    <p> Forum has been created </p>
    

app/views/forums/edit.html.erb
    <h2> Edit page is under construction </h2>
    <p> But still, routing works, doesn't it? </p>

     <h2> Edit forum </h2>

    <%= form_for :forum, url:forums_path(@forum) do |f| %>

    <p>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.text_area :description %>

    </p>

    <p>
        <%= f.submit "Edit forum" %>    
    </p>
    <% end %>

app/views/forums/index.html.erb
 
<table>
  <tr>
    <th width="70%">Forum</th>
    <th width="30%">Last Post</th>
  </tr>
  <% for forum in @forums %>
    <tr>
      <td><h4><%= link_to h(forum.name), forum_path(forum) %></h4>
        <%=h forum.description %></td>
      <td class="right"></td>
      <td><%= link_to "Delete", forum_path(forum) %></td>
      <td><%= link_to "Edit", edit_forum_path(forum) %></td>
    </tr>
  <% end %>
</table>
 
 <p><%= link_to "New Forum", new_forum_path %></p>

app/views/forums/new.html.erb
    <h2> Create new forum </h2>

    <%= form_for :forum, url:forums_path do |f| %>

    <p>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.text_area :description %>

    </p>

    <p>
        <%= f.submit "Create forum" %>    
    </p>
    <% end %>

app/views/forums/show.html.erb
    <h2> Show method, dunno why </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>